In [1]:
# Tensor is an like an data structure in machine learning used to store the Numerical data.
# Machine learning library like Tenserflow and pytorch is based on the Tensor , Tensor is most important factor in those libraryes
# Tenor Act as an container for storing the numerical data

In [2]:
import numpy as np

## 0D Tensor (Scaler)


In [5]:
arr=np.array(10)
arr

array(10)

In [4]:
arr.ndim

0

## 1D Tensor(Vector)

In [7]:
d_arr=np.array([1,2,3,4,5])    # Its an 1D Tensor but 5D Vector (Element Present in the vector) )
d_arr

array([1, 2, 3, 4, 5])

In [8]:
d_arr.ndim

1

## 2D Tensor (Matrix)

In [10]:
d_arr=np.array([[1,2,3],
               [4,5,6]])
d_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
d_arr.ndim                # This is an 2D array or collection of vectors

2

In [13]:
## 3D Tensor 

d_arr=np.array([[
    [1,2,3],[4,5,6]
],
   [ [6,7,8],[9,10,11]
               
               ] ])

In [14]:
d_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [15]:
d_arr.ndim

3